//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP229_assignment01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Cuisine { get; set; }
        public string Category { get; set; }
        public string Descriptions { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
    }
}
