//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP229_assignment01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> CookingTime { get; set; }
        public int CuisineId { get; set; }
        public bool IsPrivate { get; set; }
        public string Description { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Cuisine Cuisine { get; set; }
    }
}
